modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License v3.1"
[[mods]]
modId="cold_sweat"
version="${file.jarVersion}"
displayName="Cold Sweat"
#logoFile="cold_sweat.png"
authors="iMikul, chubbymomo, skinnymomo"
description='''
Cold Sweat is a highly-extensible temperature mod for Minecraft. See the documentation here:
https://mikul.gitbook.io/cold-sweat/
'''
[[dependencies.cold_sweat]]
   modId="forge"
   mandatory=true
   versionRange="[43,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.cold_sweat]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.4,1.20)"
   ordering="NONE"
   side="BOTH"
